version: 2
sources:
  - name: raw
    database: weather-analytics-484616
    schema: weather_analytics
    tables:
      - name: weather
        description: "Raw weather data ingested from various sources."
        freshness:
          warn_after: {count: 2, period: day}